---
- name: Install and enable EPEL
  yum:
    name: epel-release
  when: centos_base_enable_epel

- name: Install basic packages
  yum:
    name: "{{ item }}"
  with_items:
    - git
    - gcc
    - kernel-devel
    - kernel-headers
    - sqlite-devel
    - sqlite
    - bzip2-devel
    - readline-devel
    - tcl-devel
    - libcurl
    - openssl-devel
    - zlib-static
    - python-virtualenv
    - yum-cron
    - yum-utils
    - which
    - bzip2
    - gzip
  when: centos_base_basic_packages

- name: Install the 'Development tools' package group
  yum:
    name: "@Development tools"
  when: centos_base_basic_packages

- name: Install SELinux packages
  yum:
    name: "{{ item }}"
  with_items:
    - policycoreutils
    - policycoreutils-python
    - selinux-policy
    - selinux-policy-targeted
    - libselinux-utils
    - setroubleshoot-server
    - setools
    - setools-console
    - mcstrans
  when: centos_base_selinux_packages

- name: Install utility packages
  yum:
    name: "{{ item }}"
  with_items:
    - vim-enhanced
    - cifs-utils
    - screen
    - htop
    - tree
    - wget
  when: centos_base_utility_packages

- name: Install zlib packages from EPEL
  yum:
    name: "{{ item }}"
  with_items:
    - zlib-ada-devel
    - zlib-ada
  when:
    - centos_base_enable_epel
    - centos_base_basic_packages

- name: Install debugging packages
  yum:
    name: "{{ item }}"
  with_items:
    - strace
    - mtr
    - traceroute
    - nmap
    - iotop
    - vnstat
    - sysstat
  when: centos_base_debug_packages

- name: Install packages specific to CentOS 6
  yum:
    name: "{{ item }}"
  with_items:
    - fail2ban
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "6"
    - centos_base_enable_epel

- name: Install packages specific to CentOS 7
  yum: "{{ item }}"
  with_items:
    - fail2ban-all
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"
    - centos_base_enable_epel
    - centos_base_fail2ban_configuration

- name: Install firewalld
  yum:
    name: firewalld
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"
    - centos_base_security_packages
    - centos_base_firewalld

- name: vim alias in .bashrc
  lineinfile: dest=/root/.bashrc line="alias vi=vim" state=present
  when: centos_base_basic_vim_tweaks

- name: .vimrc file
  template: dest=/root/ src=root/.vimrc
  when: centos_base_basic_vim_tweaks

- name: LOCKPRG to avoid locking of GNU screen sessions
  lineinfile: dest=/root/.bashrc line='export LOCKPRG="/bin/true"' state=present
  when: centos_base_lockprg

- name: Create htop direcotry
  file:
    path: /root/.config/htop
    state: directory
  when: centos_base_htop_configuration

- name: Configure htop
  template:
    src: root/.config/htop/htoprc
    dest: /root/.config/htop
  when: centos_base_htop_configuration

- name: Ensure fail2ban service is enabled and started
  service: name=fail2ban state=started enabled=yes
  when: centos_base_fail2ban_configuration

# Allow user to control /etc/fail2ban/jail.local
- name: Secure Fail2ban configuration
  template:
    src: etc/fail2ban/jail.d/centos_base.conf
    dest: /etc/fail2ban/jail.d
  when: centos_base_fail2ban_configuration

- name: Secure SSH configuration
  template: src=etc/ssh/sshd_config dest=/etc/ssh
  notify: sshd restart
  when: centos_base_secure_sshd

- name: Ensure firewalld is started and enabled
  systemd:
    name: firewalld
    state: started
    enabled: yes
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"
    - centos_base_basic_packages
    - centos_base_firewalld

- name: Enable firewalld services
  firewalld:
    permanent: "{{ item[1] }}"
    service: "{{ item[0] }}"
    state: enabled
    zone: public
  with_nested:
    - '{{ centos_base_firewalld_services }}'
    - [yes, no]
  notify:
    - firewalld restart
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"
    - centos_base_firewalld_services
    - centos_base_firewalld
