---
- name: Install and enable EPEL
  yum:
    name: epel-release
  when: centos_base_enable_epel|bool

- name: Install development packages
  yum:
    name:
      - git
      - gcc
      - kernel-devel
      - kernel-headers
      - sqlite-devel
      - sqlite
      - bzip2-devel
      - readline-devel
      - tcl-devel
      - libcurl
      - openssl-devel
      - which
      - bzip2
      - gzip
      - vim-enhanced
  when: centos_base_development_packages|bool

- name: Install basic packages EL 6 and 7
  yum:
    name:
      - python-virtualenv
      - yum-cron
      - yum-utils
  when:
    - centos_base_basic_packages|bool
    - ansible_distribution_major_version == "6" or ansible_distribution_major_version == "7"

- name: Install basic packages EL 8
  yum:
    name:
      - python3-virtualenv
  when:
    - centos_base_basic_packages|bool
    - ansible_distribution_major_version == "8"

- name: Install the 'Development tools' package group
  yum:
    name: "@Development tools"
  when: centos_base_basic_packages|bool

- name: Install SELinux packages for CentOS 6 and CentOS 7
  yum:
    name:
      - policycoreutils
      - policycoreutils-python
      - selinux-policy
      - selinux-policy-targeted
      - libselinux-utils
      - setroubleshoot-server
      - setools
      - setools-console
      - mcstrans
      - policycoreutils-devel
      - setroubleshoot
  when:
    - centos_base_selinux_packages|bool
    - ansible_distribution_major_version == "6" or ansible_distribution_major_version == "7"

- name: Install SELinux packages for CentOS 8
  yum:
    name:
      - policycoreutils-python-utils
  when:
    - centos_base_selinux_packages|bool
    - ansible_distribution_major_version == "8"


- name: Install utility packages
  yum:
    name:
      - vim-enhanced
      - cifs-utils
      - screen
      - htop
      - tree
      - wget
  when: centos_base_utility_packages|bool

- name: Install zlib packages from EPEL
  yum:
    name:
      - zlib-static
      - zlib-ada-devel
      - zlib-ada
  when:
    - centos_base_enable_epel|bool
    - centos_base_development_packages|bool
    - ansible_distribution_major_version == "6" or ansible_distribution_major_version == "7"

- name: Install debugging packages
  yum:
    name:
      - strace
      - mtr
      - traceroute
      - nmap
      - iotop
      - vnstat
      - sysstat
      - net-tools
  when: centos_base_debug_packages|bool

- name: Install packages specific to CentOS 6
  yum:
    name:
      - fail2ban
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "6"
    - centos_base_enable_epel|bool

- name: Install packages specific to CentOS 7
  yum:
    name:
      - fail2ban-all
      - python-inotify
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"
    - centos_base_enable_epel|bool
    - centos_base_fail2ban_configuration|bool

- name: Install firewalld
  yum:
    name: firewalld
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7" or ansible_distribution_major_version == "8"
    - centos_base_security_packages|bool
    - centos_base_firewalld|bool

- name: vim alias in .bashrc
  lineinfile:
    dest: /root/.bashrc
    line: "alias vi=vim"
    state: present
  when: centos_base_basic_vim_tweaks|bool

- name: .vimrc file
  template:
    dest: /root/
    src: root/.vimrc
  when: centos_base_basic_vim_tweaks|bool

- name: LOCKPRG to avoid locking of GNU screen sessions
  lineinfile:
    dest: /root/.bashrc
    line: 'export LOCKPRG="/bin/true"'
    state: present
  when: centos_base_lockprg|bool

- name: Create htop direcotry
  file:
    path: /root/.config/htop
    state: directory
  when: centos_base_htop_configuration|bool

- name: Configure htop
  template:
    src: root/.config/htop/htoprc
    dest: /root/.config/htop
  when: centos_base_htop_configuration|bool

- name: Ensure fail2ban service is enabled and started
  service:
    name: fail2ban
    state: started
    enabled: true
  when: centos_base_fail2ban_configuration|bool

# Allow user to control /etc/fail2ban/jail.local
- name: Secure Fail2ban configuration
  template:
    src: etc/fail2ban/jail.d/centos_base.conf
    dest: /etc/fail2ban/jail.d
  when: centos_base_fail2ban_configuration|bool

- name: Secure SSH configuration
  template:
    src: etc/ssh/sshd_config
    dest: /etc/ssh
  notify: sshd restart
  when: centos_base_secure_sshd|bool

- name: Ensure firewalld is started and enabled
  systemd:
    name: firewalld
    state: started
    enabled: true
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7" or ansible_distribution_major_version == "8"
    - centos_base_basic_packages|bool
    - centos_base_firewalld|bool

- name: Enable firewalld services
  firewalld:
    permanent: true
    service: "{{ item }}"
    state: enabled
    zone: public
  loop: '{{ centos_base_firewalld_services }}'
  notify:
    - firewalld restart
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7" or ansible_distribution_major_version == "8"
    - centos_base_firewalld_services|length > 0
    - centos_base_firewalld|bool
