---
# TODO move this playbook to a different scenario
# Default scenario must work with default variable values
- name: Converge
  hosts: all
  vars:
    - centos_base_utility_packages: true
    - centos_base_enable_epel: true
    - centos_base_vim_users: ['root']
    - centos_base_basic_vim_tweaks: true
    - centos_base_firewalld_services: ['http']
    - centos_base_basic_packages: true
    - centos_base_firewalld: true
    - centos_base_debug_packages: true
    - centos_base_security_packages: true
  pre_tasks:
    - name: Intall Apache
      yum:
        name: httpd
    - name: Start httpd
      systemd:
        name: httpd
        state: started
  roles:
    - role: ansible-role-centos_base
